from pathlib import Path

from pptx import Presentation
from pptx.util import Pt

from app.schemas.artifacts import OutputType, PresentationContent

TITLE_AND_CONTENT_LAYOUT = 1


def render_pptx(output_type: OutputType, content: dict, dest: Path) -> Path:
    if output_type != OutputType.PRESENTATION:
        raise ValueError("PPTX rendering is only supported for presentation artifacts.")

    c = PresentationContent(**content)
    prs = Presentation()

    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = c.title
    if title_slide.placeholders and len(title_slide.placeholders) > 1:
        title_slide.placeholders[1].text = "Generated by GenAI Content Transformation Platform"

    for slide_data in c.slides:
        slide = prs.slides.add_slide(prs.slide_layouts[TITLE_AND_CONTENT_LAYOUT])
        slide.shapes.title.text = slide_data.slide_title

        body = slide.placeholders[1].text_frame
        body.clear()
        for i, bullet in enumerate(slide_data.bullet_points):
            p = body.paragraphs[0] if i == 0 else body.add_paragraph()
            p.text = bullet
            p.font.size = Pt(18)

        if slide_data.speaker_notes:
            slide.notes_slide.notes_text_frame.text = slide_data.speaker_notes

    prs.save(str(dest))
    return dest
